<illerIlcelerAcilirKutu>:
BoxLayout:
    Button:
        id: iller
        text: "İl Seçiniz"
        on_release: app.iller.open(self)
        size_hint_y: None
        height: 30

    Button:
        id: ilceler
        text: "İlçe Seçiniz"
        on_release: app.ilceler.open(self)
        size_hint_y: None
        height: 30

    Button:
        id: semtler
        text: "Semt Seçiniz"
        on_release: app.semtler.open(self)
        size_hint_y: None
        height: 30

