<metinDuzenleyici>:
BoxLayout:
    orientation: "vertical"
    exit_on_escape: False
    TextInput:
        size_hint_y: 90
        id: metin
        multiline: True

    BoxLayout:
        size_hint_y: 10
        Button:
            text: "Aç"
            on_press: pass
        Button:
            text: "Kaydet"
            on_press: pass
        Button:
            text: "Farklı Kaydet"
            on_press: pass
        Button:
            text: "Yeni"
            on_press: pass
